language: php

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4  
   
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  
script:
  - vendor/bin/phpunit